services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: araujoleonardo/compras
    container_name: app
    restart: always #dev
    working_dir: /var/www/ #dev
    volumes:
      - ./:/var/www #dev
    ports:
      - "80:80" #http
      - "443:443" #https
    networks:
      - laravel11 #dev

  pgsql:
    image: postgres:16-bullseye
    container_name: pgsql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel11

  pgadmin:
    depends_on:
      - pgsql
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@gmail.com
      PGADMIN_DEFAULT_PASSWORD: teste
    networks:
      - laravel11

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - laravel11

networks:
  laravel11:
    driver: bridge
